#!/usr/bin/env node
// Builds css-only-components.css (all component styles in one file) and the
// index.html gallery from components/<name>/{index.html,style.css}.
//
//   node scripts/build.js          write both files
//   node scripts/build.js --check  exit 1 if either file is out of date

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const CSS_FILE = 'css-only-components.css';
export const GALLERY_FILE = 'index.html';

export function listComponents(root = ROOT) {
  const dir = join(root, 'components');
  return readdirSync(dir).filter((n) => statSync(join(dir, n)).isDirectory()).sort();
}

const between = (s, a, b) => {
  const i = s.indexOf(a);
  const j = s.indexOf(b, i + a.length);
  return i === -1 || j === -1 ? null : s.slice(i + a.length, j);
};

export function dedent(text) {
  const lines = text.replace(/^\s*\n/, '').replace(/\s+$/, '').split('\n');
  const indent = Math.min(...lines.filter((l) => l.trim()).map((l) => l.match(/^ */)[0].length));
  return lines.map((l) => l.slice(indent)).join('\n');
}

const unescapeHtml = (s) => s
  .replace(/&quot;/g, '"').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&');
export const escapeHtml = (s) => s
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

export function readComponent(name, root = ROOT) {
  const dir = join(root, 'components', name);
  const page = readFileSync(join(dir, 'index.html'), 'utf8');
  const css = readFileSync(join(dir, 'style.css'), 'utf8');
  const snippet = between(page, '<!-- snippet:start -->', '<!-- snippet:end -->');
  if (snippet === null) throw new Error(`components/${name}/index.html has no snippet markers`);
  const title = (page.match(/<h1>([\s\S]*?)<\/h1>/) || [])[1];
  const desc = (page.match(/<meta name="description" content="([^"]*)">/) || [])[1];
  if (!title || !desc) throw new Error(`components/${name}/index.html needs an <h1> and a meta description`);
  return { name, title: title.trim(), description: unescapeHtml(desc), html: dedent(snippet), css: css.trimEnd() + '\n' };
}

export function buildCss(root = ROOT) {
  const parts = listComponents(root).map((name) => {
    const { css } = readComponent(name, root);
    return `/* ==== ${name} (components/${name}/style.css) ==== */\n${css}`;
  });
  return [
    '/*! css-only-components | MIT License | https://github.com/ghanemja/css-only-components */',
    '/* Generated by scripts/build.js from components/<name>/style.css. Do not edit by hand. */',
    '',
    parts.join('\n'),
  ].join('\n');
}

const PAGE_CSS = `
    :root { color-scheme: light dark; font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; line-height: 1.5; }
    body { margin: 0; background: Canvas; color: CanvasText; }
    header, main { max-width: 860px; margin: 0 auto; padding: 0 16px; }
    header { padding-top: 40px; }
    header h1 { margin: 0 0 8px; }
    .toc { display: flex; flex-wrap: wrap; gap: 8px; margin: 24px 0 8px; padding: 0; list-style: none; }
    .toc a { display: inline-block; padding: 4px 12px; border: 1px solid color-mix(in srgb, currentColor 20%, transparent); border-radius: 999px; color: inherit; text-decoration: none; font-size: .875rem; }
    .toc a:hover { border-color: currentColor; }
    section { padding: 32px 0; border-top: 1px solid color-mix(in srgb, currentColor 12%, transparent); }
    section h2 { margin: 0 0 4px; }
    section > p { margin: 0 0 16px; color: color-mix(in srgb, currentColor 75%, transparent); }
    .demo { padding: 48px 24px 24px; border: 1px solid color-mix(in srgb, currentColor 15%, transparent); border-radius: 12px; }
    .demo > * + * { margin-top: 16px; }
    .links { margin: 12px 0; font-size: .875rem; }
    .code { position: relative; margin-top: 12px; }
    .code h3 { margin: 0 0 4px; font-size: .75rem; letter-spacing: .05em; text-transform: uppercase; color: color-mix(in srgb, currentColor 60%, transparent); }
    pre { margin: 0; max-height: 22rem; overflow: auto; padding: 12px 14px; border-radius: 8px; background: color-mix(in srgb, currentColor 6%, transparent); font-size: .8125rem; line-height: 1.45; tab-size: 2; }
    button { font: inherit; padding: .5rem .875rem; border-radius: .5rem; border: 1px solid color-mix(in srgb, currentColor 30%, transparent); background: Canvas; color: CanvasText; cursor: pointer; }
    .copy { position: absolute; top: 0; right: 0; padding: 2px 10px; font-size: .75rem; }
    footer { max-width: 860px; margin: 0 auto; padding: 32px 16px 64px; font-size: .875rem; color: color-mix(in srgb, currentColor 65%, transparent); }`;

const indent = (text, n) => text.split('\n').map((l) => (l ? ' '.repeat(n) + l : l)).join('\n');

export function buildGallery(root = ROOT) {
  const comps = listComponents(root).map((n) => readComponent(n, root));
  const toc = comps.map((c) => `      <li><a href="#c-${c.name}">${c.title}</a></li>`).join('\n');
  const sections = comps.map((c) => `
  <section id="c-${c.name}">
    <h2>${c.title}</h2>
    <p>${escapeHtml(c.description)}</p>
    <div class="demo">
${indent(c.html, 6)}
    </div>
    <p class="links"><a href="components/${c.name}/index.html">Open demo and accessibility notes</a></p>
    <div class="code">
      <h3>HTML</h3>
      <button type="button" class="copy" data-copy="code-${c.name}-html">Copy</button>
      <pre><code id="code-${c.name}-html">${escapeHtml(c.html)}</code></pre>
    </div>
    <div class="code">
      <h3>CSS</h3>
      <button type="button" class="copy" data-copy="code-${c.name}-css">Copy</button>
      <pre><code id="code-${c.name}-css">${escapeHtml(c.css.trimEnd())}</code></pre>
    </div>
  </section>`).join('\n');

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>css-only-components</title>
  <meta name="description" content="${comps.length} UI components built with HTML and CSS only: no JavaScript.">
  <link rel="stylesheet" href="${CSS_FILE}">
  <style>${PAGE_CSS}
  </style>
</head>
<body>
<!-- Generated by scripts/build.js. Do not edit by hand. -->
<header>
  <h1>css-only-components</h1>
  <p>${comps.length} UI components that need zero JavaScript. Copy the HTML and CSS, or include <code>${CSS_FILE}</code>. Each one has its own demo page with honest accessibility notes.</p>
  <nav aria-label="Components">
    <ul class="toc">
${toc}
    </ul>
  </nav>
</header>
<main>
${sections}
</main>
<footer>
  <p>MIT License &copy; 2026 ghanemja. The components use no JavaScript; this gallery page uses a few lines only for the Copy buttons.</p>
</footer>
<script>
  document.addEventListener('click', async (event) => {
    const btn = event.target.closest('[data-copy]');
    if (!btn) return;
    const code = document.getElementById(btn.dataset.copy);
    try {
      await navigator.clipboard.writeText(code.textContent);
      btn.textContent = 'Copied';
    } catch {
      getSelection().selectAllChildren(code);
      btn.textContent = 'Press Ctrl+C';
    }
    setTimeout(() => { btn.textContent = 'Copy'; }, 1500);
  });
</script>
</body>
</html>
`;
}

export function outputs(root = ROOT) {
  return { [CSS_FILE]: buildCss(root), [GALLERY_FILE]: buildGallery(root) };
}

function main(argv) {
  const check = argv.includes('--check');
  let stale = 0;
  for (const [file, content] of Object.entries(outputs())) {
    const path = join(ROOT, file);
    const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
    if (current === content) continue;
    if (check) {
      console.error(`${file} is out of date. Run: npm run build`);
      stale++;
    } else {
      writeFileSync(path, content);
      console.log(`wrote ${file}`);
    }
  }
  if (check && !stale) console.log('build outputs are up to date');
  return stale ? 1 : 0;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  process.exitCode = main(process.argv.slice(2));
}
