// Reads icons/<category>/<name>.svg and regenerates index.js, manifest.json
// and the icon data embedded in index.html. Run with `npm run build`.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('.', import.meta.url));
const iconsDir = join(root, 'icons');

export function collect() {
  const categories = {};
  const icons = {};
  for (const category of readdirSync(iconsDir).sort()) {
    categories[category] = [];
    for (const file of readdirSync(join(iconsDir, category)).sort()) {
      if (!file.endsWith('.svg')) continue;
      const name = file.slice(0, -4);
      if (icons[name]) throw new Error(`Duplicate icon name: ${name}`);
      icons[name] = readFileSync(join(iconsDir, category, file), 'utf8').trim();
      categories[category].push(name);
    }
  }
  return { categories, icons };
}

export function renderIndex({ categories, icons }) {
  return `// Generated by build.js — do not edit by hand.
// Icons: CC0 1.0. Code: MIT.

/** Icon SVG strings keyed by name. */
export const icons = ${JSON.stringify(icons, null, 2)};

/** Icon names grouped by category. */
export const categories = ${JSON.stringify(categories, null, 2)};

/**
 * Return an icon's SVG markup, optionally with extra attributes.
 * @param {string} name e.g. "tractor"
 * @param {{ size?: number|string, color?: string, strokeWidth?: number|string, [attr: string]: any }} [options]
 */
export function icon(name, options = {}) {
  const svg = icons[name];
  if (!svg) throw new Error(\`Unknown icon: \${name}\`);
  const { size, color, strokeWidth, ...rest } = options;
  let out = svg;
  if (color) out = out.replace('stroke="currentColor"', \`stroke="\${color}"\`);
  if (strokeWidth != null) out = out.replace('stroke-width="2"', \`stroke-width="\${strokeWidth}"\`);
  const attrs = { ...(size != null ? { width: size, height: size } : {}), ...rest };
  const extra = Object.entries(attrs)
    .map(([k, v]) => \` \${k === 'className' ? 'class' : k}="\${String(v).replace(/"/g, '&quot;')}"\`)
    .join('');
  return out.replace('<svg ', \`<svg\${extra} \`);
}

export default icons;
`;
}

export function renderManifest({ categories }) {
  const list = [];
  for (const [category, names] of Object.entries(categories))
    for (const name of names) list.push({ name, category, file: `icons/${category}/${name}.svg` });
  return JSON.stringify({ name: 'niche-icons', viewBox: '0 0 24 24', strokeWidth: 2, count: list.length, icons: list }, null, 2) + '\n';
}

export function renderGalleryData({ categories, icons }) {
  const compact = Object.fromEntries(Object.entries(icons).map(([k, v]) => [k, v.replace(/\n\s*/g, '')]));
  return `/* ICONS:START */\nconst CATEGORIES = ${JSON.stringify(categories)};\nconst ICONS = ${JSON.stringify(compact)};\n/* ICONS:END */`;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const data = collect();
  writeFileSync(join(root, 'index.js'), renderIndex(data));
  writeFileSync(join(root, 'manifest.json'), renderManifest(data));
  const htmlPath = join(root, 'index.html');
  const html = readFileSync(htmlPath, 'utf8');
  writeFileSync(htmlPath, html.replace(/\/\* ICONS:START \*\/[\s\S]*?\/\* ICONS:END \*\//, renderGalleryData(data)));
  console.log(`Built ${Object.keys(data.icons).length} icons in ${Object.keys(data.categories).length} categories.`);
}
