// Generated by build.js — do not edit by hand.
// Icons: CC0 1.0. Code: MIT.

/** Icon SVG strings keyed by name. */
export const icons = {
  "barn": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M3 21V11l3-5 6-3 6 3 3 5v10\"/>\n  <path d=\"M2 21h20\"/>\n  <path d=\"M9 21v-7h6v7\"/>\n  <path d=\"M9 14l6 7\"/>\n  <path d=\"M15 14l-6 7\"/>\n  <path d=\"M10 9h4\"/>\n</svg>",
  "chicken": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M10 7a3 3 0 0 0-6 0v5a7 7 0 0 0 7 7h2a7 7 0 0 0 7-7V7l-4 3h-6z\"/>\n  <path d=\"M5 4.5a2 2 0 0 1 4 0\"/>\n  <path d=\"M4 8 2 9l2 1\"/>\n  <path d=\"M7 7h.01\"/>\n  <path d=\"M10 14c1.5 1.5 3.5 2 5.5 1\"/>\n  <path d=\"M10 19v3\"/>\n  <path d=\"M14 19v3\"/>\n</svg>",
  "cow": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M8 15V8h8v7\"/>\n  <rect x=\"7\" y=\"14\" width=\"10\" height=\"7\" rx=\"3.5\"/>\n  <path d=\"M10 17.5h.01\"/>\n  <path d=\"M14 17.5h.01\"/>\n  <path d=\"M10 11h.01\"/>\n  <path d=\"M14 11h.01\"/>\n  <path d=\"M8 9H4.5a1.5 1.5 0 0 0 0 3H8\"/>\n  <path d=\"M16 9h3.5a1.5 1.5 0 0 1 0 3H16\"/>\n  <path d=\"M9 8C8.5 6 7.5 4.5 6 3\"/>\n  <path d=\"M15 8c.5-2 1.5-3.5 3-5\"/>\n</svg>",
  "egg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M12 2c-3.5 0-7 6-7 11a7 7 0 0 0 14 0c0-5-3.5-11-7-11z\"/>\n  <path d=\"M9 14a3 3 0 0 0 2 3\"/>\n</svg>",
  "fence": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M3 21V6l1.5-2L6 6v15\"/>\n  <path d=\"M10.5 21V6L12 4l1.5 2v15\"/>\n  <path d=\"M18 21V6l1.5-2L21 6v15\"/>\n  <path d=\"M6 9h4.5M13.5 9H18\"/>\n  <path d=\"M6 15h4.5M13.5 15H18\"/>\n  <path d=\"M2 21h20\"/>\n</svg>",
  "hay-bale": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <circle cx=\"7\" cy=\"14\" r=\"5\"/>\n  <path d=\"M7 9h10a5 5 0 0 1 0 10H7\"/>\n  <path d=\"M7 14h.01\"/>\n  <path d=\"M12 9.5v9\"/>\n  <path d=\"M16 9.5v9\"/>\n</svg>",
  "scarecrow": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M7 5h10\"/>\n  <path d=\"M9 5l1-3h4l1 3\"/>\n  <circle cx=\"12\" cy=\"8\" r=\"3\"/>\n  <path d=\"M3 13h18\"/>\n  <path d=\"M8.5 13 8 19h8l-.5-6\"/>\n  <path d=\"M12 19v3\"/>\n  <path d=\"M3 13l-1 1.5\"/>\n  <path d=\"M21 13l1 1.5\"/>\n</svg>",
  "seedling": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M12 21v-9\"/>\n  <path d=\"M12 12C12 8 9.5 6 4 6c0 4 2.5 6 8 6z\"/>\n  <path d=\"M12 10c0-3 2-5 7-5 0 3-2 5-7 5z\"/>\n  <path d=\"M7 21h10\"/>\n</svg>",
  "shovel": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M17 3l4 4\"/>\n  <path d=\"M19 5l-9 9\"/>\n  <path d=\"M8 12 3.5 16.5C2.5 17.5 2 20 2 22c2 0 4.5-.5 5.5-1.5L12 16z\"/>\n</svg>",
  "silo": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M6 21V8a6 6 0 0 1 12 0v13\"/>\n  <path d=\"M3 21h18\"/>\n  <path d=\"M6 11h12\"/>\n  <path d=\"M6 16h12\"/>\n</svg>",
  "tractor": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <circle cx=\"7\" cy=\"16\" r=\"4\"/>\n  <path d=\"M7 16h.01\"/>\n  <circle cx=\"18\" cy=\"18\" r=\"2\"/>\n  <path d=\"M4 12V5h6l2 7\"/>\n  <path d=\"M12 12h7a2 2 0 0 1 2 2v2\"/>\n  <path d=\"M11 16h5\"/>\n  <path d=\"M17 12V8\"/>\n</svg>",
  "watering-can": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M5 9h9v9a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2z\"/>\n  <path d=\"M5 11H4a2 2 0 0 0-2 2v1a2 2 0 0 0 2 2h1\"/>\n  <path d=\"M7 9V7a2 2 0 0 1 2-2h1a2 2 0 0 1 2 2v2\"/>\n  <path d=\"M14 15l6-6\"/>\n  <path d=\"M18.5 7.5l3 3\"/>\n</svg>",
  "wheat": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M12 22V7\"/>\n  <path d=\"M12 19c-2.5 0-4-1.5-4-4 2.5 0 4 1.5 4 4z\"/>\n  <path d=\"M12 19c2.5 0 4-1.5 4-4-2.5 0-4 1.5-4 4z\"/>\n  <path d=\"M12 14c-2.5 0-4-1.5-4-4 2.5 0 4 1.5 4 4z\"/>\n  <path d=\"M12 14c2.5 0 4-1.5 4-4-2.5 0-4 1.5-4 4z\"/>\n  <path d=\"M12 8c-1-1-1.5-3 0-6 1.5 3 1 5 0 6z\"/>\n</svg>",
  "atom": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M12 12h.01\"/>\n  <ellipse cx=\"12\" cy=\"12\" rx=\"10\" ry=\"3.5\"/>\n  <ellipse cx=\"12\" cy=\"12\" rx=\"10\" ry=\"3.5\" transform=\"rotate(60 12 12)\"/>\n  <ellipse cx=\"12\" cy=\"12\" rx=\"10\" ry=\"3.5\" transform=\"rotate(120 12 12)\"/>\n</svg>",
  "beaker": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M4.5 3h15\"/>\n  <path d=\"M6 3v16a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V3\"/>\n  <path d=\"M6 14h12\"/>\n  <path d=\"M10 7h2\"/>\n  <path d=\"M10 10h2\"/>\n</svg>",
  "bunsen-burner": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M7 21l1.5-3h7l1.5 3z\"/>\n  <path d=\"M10.5 18V10h3v8\"/>\n  <path d=\"M13.5 15H18\"/>\n  <path d=\"M12 2c-1.5 2-2.5 3-2.5 4.5a2.5 2.5 0 0 0 5 0C14.5 5 13.5 4 12 2z\"/>\n</svg>",
  "dna": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M7 2c0 5 10 5 10 10S7 17 7 22\"/>\n  <path d=\"M17 2c0 5-10 5-10 10s10 5 10 10\"/>\n  <path d=\"M9 5h6\"/>\n  <path d=\"M9 9h6\"/>\n  <path d=\"M9 15h6\"/>\n  <path d=\"M9 19h6\"/>\n</svg>",
  "flask-round": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M8.5 2h7\"/>\n  <path d=\"M10 2v6.5a6 6 0 1 0 4 0V2\"/>\n  <path d=\"M6.5 15h11\"/>\n</svg>",
  "flask": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M8.5 3h7\"/>\n  <path d=\"M10 3v6.5L4.3 19a1.4 1.4 0 0 0 1.2 2h13a1.4 1.4 0 0 0 1.2-2L14 9.5V3\"/>\n  <path d=\"M7 15h10\"/>\n</svg>",
  "goggles": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M4 8h16a2 2 0 0 1 2 2v3a4 4 0 0 1-4 4h-2.5L12 14l-3.5 3H6a4 4 0 0 1-4-4v-3a2 2 0 0 1 2-2z\"/>\n  <path d=\"M6 12l1.5-1.5\"/>\n  <path d=\"M15 12l1.5-1.5\"/>\n</svg>",
  "magnet": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M6 3v8a6 6 0 0 0 12 0V3h-4v8a2 2 0 0 1-4 0V3z\"/>\n  <path d=\"M6 7h4\"/>\n  <path d=\"M14 7h4\"/>\n</svg>",
  "microscope": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M5 21h14\"/>\n  <path d=\"M11 6h1a5 5 0 0 1 5 5v10\"/>\n  <rect x=\"7\" y=\"3\" width=\"4\" height=\"8\" rx=\"1\"/>\n  <path d=\"M9 11v2\"/>\n  <path d=\"M6 15h11\"/>\n</svg>",
  "petri-dish": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <ellipse cx=\"12\" cy=\"10\" rx=\"10\" ry=\"4\"/>\n  <path d=\"M2 10v4c0 2.2 4.5 4 10 4s10-1.8 10-4v-4\"/>\n  <path d=\"M9 10h.01\"/>\n  <path d=\"M14 9h.01\"/>\n  <path d=\"M12 11.5h.01\"/>\n</svg>",
  "pipette": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M14.5 7.5l5 5\"/>\n  <path d=\"M14.5 7.5l2-2a3.54 3.54 0 0 1 5 5l-2 2\"/>\n  <path d=\"M15.5 8.5 7 17l-1.5 3.5L9 19l8.5-8.5\"/>\n  <path d=\"M3 21h.01\"/>\n</svg>",
  "test-tube": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M8.5 2h7\"/>\n  <path d=\"M14 2v16a2 2 0 0 1-4 0V2\"/>\n  <path d=\"M10 12h4\"/>\n</svg>",
  "thermometer": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M9 13.5V5a2 2 0 0 1 4 0v8.5a4 4 0 1 1-4 0z\"/>\n  <path d=\"M11 17V9\"/>\n  <path d=\"M16 5h3\"/>\n  <path d=\"M16 9h3\"/>\n  <path d=\"M16 13h3\"/>\n</svg>",
  "amp": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\"/>\n  <path d=\"M3 7h18\"/>\n  <path d=\"M7 5h.01\"/>\n  <path d=\"M11 5h.01\"/>\n  <path d=\"M15 5h.01\"/>\n  <circle cx=\"12\" cy=\"14\" r=\"4\"/>\n  <path d=\"M12 14h.01\"/>\n</svg>",
  "cable": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M12 2v4\"/>\n  <path d=\"M10 6h4\"/>\n  <path d=\"M9 9h6v5a1 1 0 0 1-1 1h-4a1 1 0 0 1-1-1z\"/>\n  <path d=\"M11 15v3h2v-3\"/>\n  <path d=\"M12 18v1a3 3 0 0 1-3 3H4\"/>\n</svg>",
  "cassette": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <rect x=\"2\" y=\"5\" width=\"20\" height=\"14\" rx=\"2\"/>\n  <circle cx=\"8\" cy=\"11\" r=\"2\"/>\n  <circle cx=\"16\" cy=\"11\" r=\"2\"/>\n  <path d=\"M10 11h4\"/>\n  <path d=\"M6 19l2-4h8l2 4\"/>\n</svg>",
  "drum": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <ellipse cx=\"12\" cy=\"10\" rx=\"8\" ry=\"3\"/>\n  <path d=\"M4 10v7c0 1.66 3.58 3 8 3s8-1.34 8-3v-7\"/>\n  <path d=\"M8 12.6v7\"/>\n  <path d=\"M12 13v7\"/>\n  <path d=\"M16 12.6v7\"/>\n  <path d=\"M10 7.5 5 2\"/>\n  <path d=\"M14 7.5 19 2\"/>\n</svg>",
  "guitar": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M8.88 13.09A3.5 3.5 0 1 1 15.12 13.09A5 5 0 1 1 8.88 13.09z\"/>\n  <circle cx=\"12\" cy=\"15.5\" r=\"1.5\"/>\n  <path d=\"M10.5 19.5h3\"/>\n  <path d=\"M12 8V3\"/>\n  <path d=\"M10.5 2.5h3\"/>\n</svg>",
  "headphones": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M4 13v-1a8 8 0 0 1 16 0v1\"/>\n  <rect x=\"3\" y=\"13\" width=\"4\" height=\"8\" rx=\"2\"/>\n  <rect x=\"17\" y=\"13\" width=\"4\" height=\"8\" rx=\"2\"/>\n</svg>",
  "metronome": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M9.5 3h5l4.5 18H5z\"/>\n  <path d=\"M6 17h12\"/>\n  <path d=\"M12 17l4-9\"/>\n  <path d=\"M12.9 12.6l1.8.8\"/>\n</svg>",
  "microphone": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <circle cx=\"15\" cy=\"9\" r=\"5\"/>\n  <path d=\"M11.5 5.5l7 7\"/>\n  <path d=\"M10.8 11.8 3.9 19.4a1.06 1.06 0 0 0 1.5 1.5l6.8-7.7\"/>\n</svg>",
  "mixer": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <rect x=\"2\" y=\"3\" width=\"20\" height=\"18\" rx=\"2\"/>\n  <path d=\"M7 7v10\"/>\n  <path d=\"M12 7v10\"/>\n  <path d=\"M17 7v10\"/>\n  <path d=\"M5.5 14h3\"/>\n  <path d=\"M10.5 9h3\"/>\n  <path d=\"M15.5 12h3\"/>\n</svg>",
  "piano-keys": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <rect x=\"2\" y=\"4\" width=\"20\" height=\"16\" rx=\"2\"/>\n  <rect x=\"5.5\" y=\"4\" width=\"3\" height=\"8\" rx=\"0.5\"/>\n  <rect x=\"10.5\" y=\"4\" width=\"3\" height=\"8\" rx=\"0.5\"/>\n  <path d=\"M7 12v8\"/>\n  <path d=\"M12 12v8\"/>\n  <path d=\"M17 4v16\"/>\n</svg>",
  "tuning-fork": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M9 2v8a3 3 0 0 0 6 0V2\"/>\n  <path d=\"M12 13v8\"/>\n  <path d=\"M5 4v4\"/>\n  <path d=\"M19 4v4\"/>\n</svg>",
  "vinyl": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <circle cx=\"12\" cy=\"12\" r=\"10\"/>\n  <circle cx=\"12\" cy=\"12\" r=\"3\"/>\n  <path d=\"M12 12h.01\"/>\n  <path d=\"M6 12a6 6 0 0 1 6-6\"/>\n  <path d=\"M18 12a6 6 0 0 1-6 6\"/>\n</svg>",
  "violin": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M12 7c-2 0-4 .5-4 2.5 0 1.2 1 1.8 1 2.5s-2 1.5-2 4.5c0 2.5 2 4.5 5 4.5s5-2 5-4.5c0-3-2-3.8-2-4.5s1-1.3 1-2.5C16 7.5 14 7 12 7z\"/>\n  <path d=\"M12 2v10\"/>\n  <path d=\"M13.5 2.5a1.5 1.5 0 0 0-1.5-.5\"/>\n  <path d=\"M9.5 13c.5 1 .5 2 0 3\"/>\n  <path d=\"M14.5 13c-.5 1-.5 2 0 3\"/>\n  <path d=\"M12 16.5V19\"/>\n</svg>",
  "drill": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <rect x=\"3\" y=\"5\" width=\"14\" height=\"6\" rx=\"2\"/>\n  <path d=\"M17 6.5h2v3h-2\"/>\n  <path d=\"M19 8h3\"/>\n  <path d=\"M7 11l-1 7h4l1-7\"/>\n  <rect x=\"4\" y=\"18\" width=\"8\" height=\"3\" rx=\"1\"/>\n  <path d=\"M11 13h1.5\"/>\n</svg>",
  "hammer": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M9 6l3-3 7 7-3 3z\"/>\n  <path d=\"M11.5 8.5 3.5 16.5a1.41 1.41 0 0 0 2 2l8-8\"/>\n</svg>",
  "hard-hat": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M4 17v-3a8 8 0 0 1 16 0v3\"/>\n  <rect x=\"2\" y=\"17\" width=\"20\" height=\"3\" rx=\"1\"/>\n  <path d=\"M10 6.5V11\"/>\n  <path d=\"M14 6.5V11\"/>\n</svg>",
  "ladder": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M8 2v20\"/>\n  <path d=\"M16 2v20\"/>\n  <path d=\"M8 6h8\"/>\n  <path d=\"M8 10h8\"/>\n  <path d=\"M8 14h8\"/>\n  <path d=\"M8 18h8\"/>\n</svg>",
  "level": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <rect x=\"2\" y=\"8\" width=\"20\" height=\"8\" rx=\"2\"/>\n  <rect x=\"9\" y=\"10\" width=\"6\" height=\"4\" rx=\"2\"/>\n  <path d=\"M12 12h.01\"/>\n  <path d=\"M5 11v2\"/>\n  <path d=\"M19 11v2\"/>\n</svg>",
  "paint-roller": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <rect x=\"3\" y=\"3\" width=\"14\" height=\"6\" rx=\"2\"/>\n  <path d=\"M17 6h3a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1h-8v3\"/>\n  <rect x=\"10\" y=\"15\" width=\"4\" height=\"7\" rx=\"1\"/>\n</svg>",
  "pliers": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M10 9.5 9 3a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1l-1 6.5\"/>\n  <path d=\"M12 2v6\"/>\n  <circle cx=\"12\" cy=\"11\" r=\"2\"/>\n  <path d=\"M10.5 12.8 6.2 20.5a1 1 0 0 0 1.8.9L12 14\"/>\n  <path d=\"M13.5 12.8l4.3 7.7a1 1 0 0 1-1.8.9L12 14\"/>\n</svg>",
  "saw": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M14 8 2 11.5V15l1.5 1.5L5 15l1.5 1.5L8 15l1.5 1.5L11 15l1.5 1.5L14 15\"/>\n  <path d=\"M14 6h4a4 4 0 0 1 4 4v3a4 4 0 0 1-4 4h-4z\"/>\n  <path d=\"M17 10v3\"/>\n</svg>",
  "screwdriver": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M9 5a3 3 0 0 1 6 0v5l-1.5 2h-3L9 10z\"/>\n  <path d=\"M12 5v4\"/>\n  <path d=\"M12 12v10\"/>\n</svg>",
  "tape-measure": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M16 11v7H9a7 7 0 1 1 7-7z\"/>\n  <circle cx=\"9\" cy=\"11\" r=\"2\"/>\n  <path d=\"M16 18h6\"/>\n  <path d=\"M22 16v4\"/>\n</svg>",
  "toolbox": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <rect x=\"2\" y=\"8\" width=\"20\" height=\"12\" rx=\"2\"/>\n  <path d=\"M9 8V5a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v3\"/>\n  <path d=\"M2 13h20\"/>\n  <path d=\"M10 12v2h4v-2\"/>\n</svg>",
  "trowel": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M3 21 6 11l5 2 2 5z\"/>\n  <path d=\"M11 13l2.5-2.5\"/>\n  <path d=\"M12 9l6-6a2.12 2.12 0 0 1 3 3l-6 6z\"/>\n</svg>",
  "wrench": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n  <path d=\"M13.69 12.43A5 5 0 0 0 20.43 5.69L17.06 9.06A1.5 1.5 0 0 1 14.94 6.94L18.31 3.57A5 5 0 0 0 11.57 10.31L5.04 16.84A1.5 1.5 0 0 0 7.16 18.96z\"/>\n</svg>"
};

/** Icon names grouped by category. */
export const categories = {
  "farming": [
    "barn",
    "chicken",
    "cow",
    "egg",
    "fence",
    "hay-bale",
    "scarecrow",
    "seedling",
    "shovel",
    "silo",
    "tractor",
    "watering-can",
    "wheat"
  ],
  "lab": [
    "atom",
    "beaker",
    "bunsen-burner",
    "dna",
    "flask-round",
    "flask",
    "goggles",
    "magnet",
    "microscope",
    "petri-dish",
    "pipette",
    "test-tube",
    "thermometer"
  ],
  "music": [
    "amp",
    "cable",
    "cassette",
    "drum",
    "guitar",
    "headphones",
    "metronome",
    "microphone",
    "mixer",
    "piano-keys",
    "tuning-fork",
    "vinyl",
    "violin"
  ],
  "trades": [
    "drill",
    "hammer",
    "hard-hat",
    "ladder",
    "level",
    "paint-roller",
    "pliers",
    "saw",
    "screwdriver",
    "tape-measure",
    "toolbox",
    "trowel",
    "wrench"
  ]
};

/**
 * Return an icon's SVG markup, optionally with extra attributes.
 * @param {string} name e.g. "tractor"
 * @param {{ size?: number|string, color?: string, strokeWidth?: number|string, [attr: string]: any }} [options]
 */
export function icon(name, options = {}) {
  const svg = icons[name];
  if (!svg) throw new Error(`Unknown icon: ${name}`);
  const { size, color, strokeWidth, ...rest } = options;
  let out = svg;
  if (color) out = out.replace('stroke="currentColor"', `stroke="${color}"`);
  if (strokeWidth != null) out = out.replace('stroke-width="2"', `stroke-width="${strokeWidth}"`);
  const attrs = { ...(size != null ? { width: size, height: size } : {}), ...rest };
  const extra = Object.entries(attrs)
    .map(([k, v]) => ` ${k === 'className' ? 'class' : k}="${String(v).replace(/"/g, '&quot;')}"`)
    .join('');
  return out.replace('<svg ', `<svg${extra} `);
}

export default icons;
