#!/usr/bin/env node
// Generates COOKBOOK.md and refreshes the data block inside index.html from patterns.js.
// Usage: node scripts/build-docs.js        (write files)
//        node scripts/build-docs.js --check (exit 1 if files are out of date)
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { patterns } from '../patterns.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
export const COOKBOOK = join(root, 'COOKBOOK.md');
export const INDEX = join(root, 'index.html');
const DATA_START = '<!-- data:start -->';
const DATA_END = '<!-- data:end -->';

const CATEGORIES = {
  web: 'Web & markup',
  network: 'Network',
  identifiers: 'Identifiers & versions',
  dates: 'Dates & times',
  locale: 'Locale-specific formats',
  numbers: 'Numbers & money',
  encoding: 'Colors, encodings & passwords',
  text: 'Text editing',
};

const cell = (s) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
const code = (s) => {
  const fence = s.includes('`') ? '``' : '`';
  const pad = s.startsWith('`') || s.endsWith('`') ? ' ' : '';
  return `${fence}${pad}${s}${pad}${fence}`;
};
const anchor = (name) => name.toLowerCase().replace(/[^a-z0-9 -]/g, '').replace(/ /g, '-');

/** Render the whole cookbook as Markdown. Pure: same input, same output. */
export function renderMarkdown(list = patterns) {
  const out = [];
  out.push('# Regex Cookbook', '');
  out.push('<!-- Generated by scripts/build-docs.js from patterns.js. Do not edit by hand. -->', '');
  out.push(`${list.length} tested regular expressions. For each one, every listed example is checked by \`npm test\`: the pattern must match the "Matches" strings and must not match the "Does not match" strings, using \`new RegExp(pattern, flags).test(input)\`.`, '');
  out.push('```js', "import { get, compile, test } from 'regex-cookbook';", '', "compile('semver').exec('1.2.3-beta.1');", "test('uuid', '123e4567-e89b-12d3-a456-426614174000'); // true", '```', '');
  out.push('## Contents', '');
  const cats = [...new Set(list.map((p) => p.category))];
  for (const c of cats) {
    out.push(`- **${CATEGORIES[c] || c}**: ` + list.filter((p) => p.category === c).map((p) => `[${p.name}](#${anchor(p.name)})`).join(', '));
  }
  out.push('');
  for (const c of cats) {
    out.push(`## ${CATEGORIES[c] || c}`, '');
    for (const p of list.filter((x) => x.category === c)) {
      out.push(`### ${p.name}`, '');
      out.push(p.description, '');
      out.push('```js', `/${p.pattern}/${p.flags}`, '```', '');
      out.push('| Piece | Meaning |', '|---|---|');
      for (const [piece, meaning] of p.explanation) out.push(`| ${cell(code(piece))} | ${cell(meaning)} |`);
      out.push('');
      if (p.caveats.length) {
        out.push('**Caveats**', '');
        for (const c2 of p.caveats) out.push(`- ${c2}`);
        out.push('');
      }
      out.push('**Matches**: ' + p.matches.map((m) => code(JSON.stringify(m))).join(', '), '');
      out.push('**Does not match**: ' + p.nonMatches.map((m) => code(JSON.stringify(m))).join(', '), '');
    }
  }
  out.push('---', '', 'MIT © 2026 ghanemja', '');
  return out.join('\n');
}

/** The JSON data block embedded in index.html (so it works from file:// with no server). */
export function renderDataBlock(list = patterns) {
  const json = JSON.stringify(list).replace(/</g, '\\u003c');
  return `${DATA_START}\n<script id="cookbook-data" type="application/json">${json}</script>\n${DATA_END}`;
}

/** Replace the data block inside the given index.html text. */
export function renderIndex(html, list = patterns) {
  const s = html.indexOf(DATA_START);
  const e = html.indexOf(DATA_END);
  if (s === -1 || e < s) throw new Error('index.html is missing the data markers');
  return html.slice(0, s) + renderDataBlock(list) + html.slice(e + DATA_END.length);
}

function main() {
  const md = renderMarkdown();
  const html = readFileSync(INDEX, 'utf8');
  const nextHtml = renderIndex(html);
  if (process.argv.includes('--check')) {
    const stale = [];
    let current = '';
    try {
      current = readFileSync(COOKBOOK, 'utf8');
    } catch {}
    if (current !== md) stale.push('COOKBOOK.md');
    if (html !== nextHtml) stale.push('index.html');
    if (stale.length) {
      console.error(`Out of date: ${stale.join(', ')}. Run: npm run docs`);
      process.exit(1);
    }
    console.log('Docs are up to date.');
    return;
  }
  writeFileSync(COOKBOOK, md);
  writeFileSync(INDEX, nextHtml);
  console.log(`Wrote COOKBOOK.md and index.html (${patterns.length} patterns).`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
