// The cookbook data. Every entry is plain data:
//   name, category, pattern (RegExp source string), flags, description,
//   explanation: [[piece, meaning], ...], caveats: [...],
//   matches / nonMatches: strings for which `new RegExp(pattern, flags).test(s)` is true / false.
// Run `npm run docs` after editing to regenerate COOKBOOK.md and index.html.
const r = String.raw;

export const patterns = [
  // ---------------------------------------------------------------- web
  {
    name: 'email-simple',
    category: 'web',
    pattern: r`^[^\s@]+@[^\s@]+\.[^\s@]+$`,
    flags: '',
    description: 'A pragmatic email check: something, an @, something, a dot, something. No spaces, exactly one @.',
    explanation: [
      ['^', 'start of the string'],
      [r`[^\s@]+`, 'local part: one or more characters that are not whitespace or @'],
      ['@', 'a single literal @'],
      [r`[^\s@]+`, 'domain name (at least one character)'],
      [r`\.`, 'a literal dot'],
      [r`[^\s@]+`, 'top-level domain (anything without spaces or @)'],
      ['$', 'end of the string'],
    ],
    caveats: [
      'Deliberately loose: it accepts many technically invalid addresses (like `a@b.c`) and rejects only unusual valid ones, such as quoted local parts containing spaces or `@`.',
      'The only real email validation is sending a confirmation message.',
    ],
    matches: ['a@b.co', 'john.doe@example.com', 'user+tag@sub.domain.org', 'x_y@foo.io'],
    nonMatches: ['plainaddress', '@no-local.com', 'user@nodot', 'user name@example.com', 'a@b@c.com'],
  },
  {
    name: 'url',
    category: 'web',
    pattern: r`^https?:\/\/(?:[\w-]+\.)+[a-z]{2,}(?::\d{2,5})?(?:[\/?#]\S*)?$`,
    flags: 'i',
    description: 'An absolute http or https URL with a dotted host name, optional port, and optional path, query, or fragment.',
    explanation: [
      ['^https?', '`http` with an optional `s`'],
      [r`:\/\/`, 'the `://` separator'],
      [r`(?:[\w-]+\.)+`, 'one or more host labels, each followed by a dot (`www.`, `example.`)'],
      ['[a-z]{2,}', 'top-level domain of two or more letters'],
      [r`(?::\d{2,5})?`, 'optional port such as `:8080`'],
      [r`(?:[\/?#]\S*)?`, 'optional path, query or fragment: starts with `/`, `?` or `#`, then anything but whitespace'],
      ['$', 'end of the string'],
      ['i flag', 'scheme and host are case-insensitive'],
    ],
    caveats: [
      'Rejects `localhost`, bare IP addresses and internationalized (non-ASCII) host names.',
      'In JavaScript, `new URL(str)` inside try/catch is a stricter and more complete check.',
    ],
    matches: ['https://example.com', 'http://sub.example.co.uk/path?q=1#frag', 'https://example.com:8080/a', 'HTTPS://EXAMPLE.ORG'],
    nonMatches: ['ftp://example.com', 'http://', 'example.com', 'https://exa mple.com', 'http://localhost'],
  },
  {
    name: 'domain',
    category: 'web',
    pattern: r`^(?=.{1,253}$)(?:(?!-)[a-z0-9-]{1,63}(?<!-)\.)+[a-z]{2,63}$`,
    flags: 'i',
    description: 'A fully qualified domain name: dot-separated labels of up to 63 characters that do not start or end with a hyphen.',
    explanation: [
      ['^(?=.{1,253}$)', 'lookahead: the whole name is at most 253 characters'],
      ['(?!-)', 'a label may not start with a hyphen'],
      ['[a-z0-9-]{1,63}', 'label of 1 to 63 letters, digits or hyphens'],
      ['(?<!-)', 'lookbehind: a label may not end with a hyphen'],
      [r`\.`, 'dot after each label'],
      ['(?: ... )+', 'one or more labels'],
      ['[a-z]{2,63}$', 'a letters-only top-level domain'],
    ],
    caveats: [
      'Punycode (`xn--`) names pass. Raw Unicode names do not, so convert them first with `new URL()`.',
      'Requires at least one dot, so single-label hosts like `localhost` fail.',
    ],
    matches: ['example.com', 'sub.example.co.uk', 'my-site.io', 'xn--bcher-kva.example'],
    nonMatches: ['-bad.com', 'bad-.com', 'localhost', 'exa_mple.com', 'example..com', 'example.c'],
  },
  {
    name: 'slug',
    category: 'web',
    pattern: r`^[a-z0-9]+(?:-[a-z0-9]+)*$`,
    flags: '',
    description: 'A URL slug: lowercase letters and digits in groups joined by single hyphens.',
    explanation: [
      ['^[a-z0-9]+', 'starts with at least one lowercase letter or digit'],
      ['(?:-[a-z0-9]+)*', 'any number of groups, each a hyphen followed by letters or digits'],
      ['$', 'end of the string, so there is no trailing hyphen'],
    ],
    caveats: ['ASCII only. Run the input through a slugify step first if it has accents or non-Latin text.'],
    matches: ['hello-world', 'a', 'post-123', '2026-recap'],
    nonMatches: ['Hello-World', '-leading', 'trailing-', 'double--dash', 'with space'],
  },
  {
    name: 'html-tag',
    category: 'web',
    pattern: r`<\/?([a-z][a-z0-9-]*)\b[^>]*>`,
    flags: 'i',
    description: 'Finds an opening, closing or self-closing HTML tag and captures the tag name.',
    explanation: [
      ['<', 'opening angle bracket'],
      [r`\/?`, 'optional `/` for closing tags'],
      ['([a-z][a-z0-9-]*)', 'group 1: tag name, starting with a letter (custom elements may contain hyphens)'],
      [r`\b`, 'word boundary, so `<divx` is not read as `div`'],
      ['[^>]*', 'attributes: anything up to the next `>`'],
      ['>', 'closing angle bracket'],
    ],
    caveats: [
      'Regex cannot parse HTML. A `>` inside an attribute value (`title="a>b"`) ends the match early, and comments, CDATA and scripts are not understood.',
      'Use `DOMParser` or a real HTML parser for anything beyond quick searches.',
    ],
    matches: ['<div>', '</p>', '<img src="a.png" />', '<my-element data-x="1">', 'text <br> text'],
    nonMatches: ['a < b', '<>', '<1div>', 'plain text'],
  },
  {
    name: 'markdown-link',
    category: 'web',
    pattern: r`(?<!!)\[([^\]]+)\]\(([^)\s]+)(?:\s+"([^"]*)")?\)`,
    flags: '',
    description: 'Finds an inline Markdown link `[text](url "title")` but not an image `![alt](src)`. Captures text, URL and optional title.',
    explanation: [
      ['(?<!!)', 'lookbehind: the `[` must not follow a `!`, which would make it an image'],
      [r`\[([^\]]+)\]`, 'group 1: link text inside square brackets (not empty)'],
      [r`\(([^)\s]+)`, 'group 2: URL after `(`, with no spaces or `)`'],
      [r`(?:\s+"([^"]*)")?`, 'optional group 3: a title in double quotes'],
      [r`\)`, 'closing parenthesis'],
    ],
    caveats: [
      'Nested brackets in the text, URLs with parentheses (some Wikipedia links), angle-bracket URLs and reference-style links `[text][id]` are not handled.',
    ],
    matches: ['[text](https://x.com)', 'see [docs](./docs.md) here', '[a](b "title")', '[x](#anchor)'],
    nonMatches: ['![img](a.png)', '[text] (url)', '[](empty)', '(url)[text]', '[text](has space)'],
  },
  {
    name: 'hashtag',
    category: 'web',
    pattern: r`(?<![\w#&])#(\w*[A-Za-z_]\w*)`,
    flags: '',
    description: 'Finds a social-media hashtag. It must contain at least one letter, so `#123` (an issue number) does not count.',
    explanation: [
      ['(?<![\\w#&])', 'lookbehind: not preceded by a word character, `#` or `&`. This skips `a#b`, `##`, and HTML entities like `&#39;`'],
      ['#', 'the hash sign'],
      [r`(\w*[A-Za-z_]\w*)`, 'group 1: the tag, made of word characters with at least one letter or underscore'],
    ],
    caveats: [
      '`\\w` is ASCII-only in JavaScript. For tags like `#café` use `[\\p{L}\\p{N}_]` with the `u` flag.',
      'CSS colors such as `#fff` also match, so filter them out by context if needed.',
    ],
    matches: ['#javascript', 'I love #regex!', '#100DaysOfCode', 'tags: #a_b'],
    nonMatches: ['issue #123', 'a#b', '&#39;', '# heading', '##double'],
  },
  {
    name: 'mention',
    category: 'web',
    pattern: r`(?<![\w.@])@([A-Za-z0-9_]{1,30})(?![\w@])`,
    flags: '',
    description: 'Finds an @mention such as `@jane` while skipping the @ inside email addresses.',
    explanation: [
      [r`(?<![\w.@])`, 'lookbehind: the @ must not follow a word character, dot or @. This skips `user@example.com`'],
      ['@', 'the at sign'],
      ['([A-Za-z0-9_]{1,30})', 'group 1: the handle, 1 to 30 letters, digits or underscores'],
      [r`(?![\w@])`, 'lookahead: the handle must end here, so names longer than 30 characters fail instead of being cut short'],
    ],
    caveats: ['Handle rules differ by platform. GitHub allows hyphens and X/Twitter caps handles at 15 characters, so adjust the character class and length.'],
    matches: ['@jane', 'hey @john_doe!', 'cc @dev42, thanks', '(@team)'],
    nonMatches: ['email@example.com', '@ alone', '@@double', 'no mention here', '@this_handle_is_way_too_long_for_us'],
  },
  {
    name: 'file-extension',
    category: 'web',
    pattern: r`(?<=[^\/\\.])\.([a-z0-9]+)$`,
    flags: 'i',
    description: 'Captures the extension at the end of a file name or path (`gz` in `archive.tar.gz`). Dotfiles like `.bashrc` have no extension.',
    explanation: [
      [r`(?<=[^\/\\.])`, 'lookbehind: the dot must follow a character that is not a slash, backslash or dot, so a leading dot does not count'],
      [r`\.`, 'the last dot'],
      ['([a-z0-9]+)', 'group 1: the extension'],
      ['$', 'must be at the very end, so dots in folder names are ignored'],
    ],
    caveats: ['Only the last extension is captured. For `.tar.gz` style double extensions, use `(\\.[a-z0-9]+)+$`.'],
    matches: ['photo.jpg', 'archive.tar.gz', 'README.md', '/path/to/file.TXT'],
    nonMatches: ['Makefile', 'folder/', 'file.', '.bashrc', 'my.folder/file'],
  },

  // ---------------------------------------------------------------- network
  {
    name: 'ipv4',
    category: 'network',
    pattern: r`^(?:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)\.){3}(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)$`,
    flags: '',
    description: 'A dotted-quad IPv4 address with each octet between 0 and 255 and no leading zeros.',
    explanation: [
      ['25[0-5]', '250 to 255'],
      [r`2[0-4]\d`, '200 to 249'],
      [r`1\d\d`, '100 to 199'],
      [r`[1-9]?\d`, '0 to 99, without a leading zero'],
      [r`(?:octet\.){3}`, 'three octets, each followed by a dot'],
      ['(?:octet)$', 'the fourth octet, then the end of the string'],
    ],
    caveats: ['Leading zeros (`010.0.0.1`) are rejected on purpose because some parsers read them as octal.', 'CIDR suffixes like `/24` are not accepted.'],
    matches: ['192.168.1.1', '0.0.0.0', '255.255.255.255', '10.0.0.254'],
    nonMatches: ['256.1.1.1', '1.2.3', '01.2.3.4', '1.2.3.4.5', 'a.b.c.d'],
  },
  {
    name: 'ipv6',
    category: 'network',
    pattern: r`^(?:(?:[0-9a-f]{1,4}:){7}[0-9a-f]{1,4}|(?:[0-9a-f]{1,4}:){1,7}:|(?:[0-9a-f]{1,4}:){1,6}:[0-9a-f]{1,4}|(?:[0-9a-f]{1,4}:){1,5}(?::[0-9a-f]{1,4}){1,2}|(?:[0-9a-f]{1,4}:){1,4}(?::[0-9a-f]{1,4}){1,3}|(?:[0-9a-f]{1,4}:){1,3}(?::[0-9a-f]{1,4}){1,4}|(?:[0-9a-f]{1,4}:){1,2}(?::[0-9a-f]{1,4}){1,5}|[0-9a-f]{1,4}:(?::[0-9a-f]{1,4}){1,6}|:(?:(?::[0-9a-f]{1,4}){1,7}|:))$`,
    flags: 'i',
    description: 'An IPv6 address in full or `::`-compressed form.',
    explanation: [
      ['[0-9a-f]{1,4}', 'one group of 1 to 4 hex digits ("h" below)'],
      ['(?:h:){7}h', 'the full form: eight groups'],
      ['(?:h:){1,7}:', 'compressed at the end, e.g. `fe80::`'],
      ['(?:h:){n}(?::h){m}', 'the middle alternatives: `::` replaces a run of zero groups somewhere in the middle, with n + m ≤ 7'],
      ['h:(?::h){1,6}', 'compressed right after the first group'],
      ['(?:(?::h){1,7}|:)', 'compressed at the start, e.g. `::1`, or the bare `::`'],
      ['i flag', 'hex digits in either case'],
    ],
    caveats: [
      'Zone IDs (`fe80::1%eth0`) and embedded IPv4 (`::ffff:192.0.2.1`) are not accepted.',
      'Node has `net.isIPv6()` built in. Use it when you can.',
    ],
    matches: ['2001:0db8:85a3:0000:0000:8a2e:0370:7334', '2001:db8::1', '::1', '::', 'fe80::', 'FE80::1:2'],
    nonMatches: ['2001:db8:::1', '12345::', '1:2:3:4:5:6:7:8:9', 'g::1', '192.168.1.1'],
  },
  {
    name: 'mac-address',
    category: 'network',
    pattern: r`^[0-9a-f]{2}([:-])(?:[0-9a-f]{2}\1){4}[0-9a-f]{2}$`,
    flags: 'i',
    description: 'A 48-bit MAC address written as six hex pairs with one separator style (`:` or `-`) throughout.',
    explanation: [
      ['^[0-9a-f]{2}', 'first hex pair'],
      ['([:-])', 'group 1: the separator, either `:` or `-`'],
      [r`(?:[0-9a-f]{2}\1){4}`, 'four more pairs, each followed by the same separator (`\\1` is a backreference)'],
      ['[0-9a-f]{2}$', 'the last pair'],
    ],
    caveats: ['Cisco dotted notation (`001a.2b3c.4d5e`) and bare 12-digit forms are not accepted.'],
    matches: ['00:1A:2B:3C:4D:5E', '00-1a-2b-3c-4d-5e', 'ff:ff:ff:ff:ff:ff', 'a1:b2:c3:d4:e5:f6'],
    nonMatches: ['00:1A-2B:3C:4D:5E', '001A2B3C4D5E', '00:1A:2B:3C:4D', 'GG:1A:2B:3C:4D:5E'],
  },

  // ---------------------------------------------------------------- identifiers
  {
    name: 'uuid',
    category: 'identifiers',
    pattern: r`^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`,
    flags: 'i',
    description: 'An RFC 9562 UUID, versions 1 through 8, in the canonical 8-4-4-4-12 hyphenated form.',
    explanation: [
      ['[0-9a-f]{8}-', '8 hex digits'],
      ['[0-9a-f]{4}-', '4 hex digits'],
      ['[1-8][0-9a-f]{3}-', 'version nibble 1 to 8, then 3 hex digits'],
      ['[89ab][0-9a-f]{3}-', 'variant nibble `8`, `9`, `a` or `b` (RFC variant), then 3 hex digits'],
      ['[0-9a-f]{12}', '12 hex digits'],
    ],
    caveats: ['The nil UUID (all zeros) and the max UUID (all `f`) are rejected. Allow them explicitly if you need them.', 'Braced `{...}` and URN `urn:uuid:` forms are not accepted.'],
    matches: ['123e4567-e89b-12d3-a456-426614174000', '550e8400-e29b-41d4-a716-446655440000', 'F47AC10B-58CC-4372-A567-0E02B2C3D479', '01890a5d-ac96-774b-bcce-b302099a8057'],
    nonMatches: ['00000000-0000-0000-0000-000000000000', '123e4567e89b12d3a456426614174000', '123e4567-e89b-12d3-c456-426614174000', 'g23e4567-e89b-12d3-a456-426614174000', '123e4567-e89b-12d3-a456-42661417400'],
  },
  {
    name: 'semver',
    category: 'identifiers',
    pattern: r`^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$`,
    flags: '',
    description: 'A Semantic Versioning 2.0.0 version string, using the official regex from semver.org. It captures major, minor, patch, prerelease and build.',
    explanation: [
      [r`(0|[1-9]\d*)`, 'groups 1 to 3: major, minor and patch, as non-negative integers without leading zeros'],
      [r`\.`, 'dots between them'],
      [r`(?:-(...))?`, 'optional group 4: prerelease after `-`, as dot-separated identifiers'],
      [r`0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*`, 'a prerelease identifier is a number without leading zeros or an alphanumeric string'],
      [r`(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?`, 'optional group 5: build metadata after `+`'],
    ],
    caveats: ['A leading `v` (`v1.2.3`) is not part of semver, so strip it first.', 'Ranges like `^1.2.0` are not versions and do not match.'],
    matches: ['1.0.0', '0.1.2-alpha.1', '2.3.4+build.5', '1.0.0-rc.1+sha.abc123'],
    nonMatches: ['1.0', 'v1.0.0', '01.0.0', '1.0.0-', '1.0.0-01'],
  },
  {
    name: 'git-sha',
    category: 'identifiers',
    pattern: r`^(?:[0-9a-f]{7,40}|[0-9a-f]{64})$`,
    flags: '',
    description: 'A git commit hash: an abbreviated or full SHA-1 (7 to 40 hex digits) or a full SHA-256 (64 hex digits).',
    explanation: [
      ['[0-9a-f]{7,40}', 'SHA-1, from the shortest usual abbreviation (7) up to full length (40)'],
      ['|[0-9a-f]{64}', 'or a full SHA-256 object name'],
      ['^ ... $', 'the whole string is the hash'],
    ],
    caveats: ['Git prints lowercase hex, so uppercase is rejected. Add the `i` flag if your input may be uppercase.', 'Any hex word of 7 or more characters, such as `deadbeef`, will pass.'],
    matches: ['a1b2c3d', '3f786850e387550fdab836ed7e6dc881de23001b', 'deadbeef', '6e340b9cffb37a989ca544e6bb780a2c78901d3fb33738768511a30617afa01d'],
    nonMatches: ['abc123', 'g1b2c3d', '3F786850E', '3f786850e387550fdab836ed7e6dc881de23001b0'],
  },
  {
    name: 'username',
    category: 'identifiers',
    pattern: r`^(?=.{3,16}$)[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$`,
    flags: 'i',
    description: 'A username of 3 to 16 characters that starts with a letter. Single `.`, `_` or `-` separators are allowed between letters and digits.',
    explanation: [
      ['^(?=.{3,16}$)', 'lookahead: the total length is 3 to 16'],
      ['[a-z]', 'must start with a letter'],
      ['[a-z0-9]*', 'then letters or digits'],
      ['(?:[._-][a-z0-9]+)*', 'optional groups of one separator followed by letters or digits, so the name never ends with a separator and never has two in a row'],
    ],
    caveats: ['These rules vary by product. Change the length limits and separators to fit yours.'],
    matches: ['jane', 'john_doe', 'j.smith', 'dev-ops42'],
    nonMatches: ['ab', '1user', 'user_', 'jo__hn', 'averyveryverylongusername'],
  },
  {
    name: 'jwt',
    category: 'identifiers',
    pattern: r`^eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]*$`,
    flags: '',
    description: 'The shape of a JSON Web Token: three base64url segments separated by dots. The header starts with `eyJ`, which is the encoding of `{"`.',
    explanation: [
      ['^eyJ', 'header: base64url of `{"`, which every JSON object header starts with'],
      ['[A-Za-z0-9_-]+', 'the rest of the header in the base64url alphabet (no `+`, `/` or `=`)'],
      [r`\.[A-Za-z0-9_-]+`, 'dot, then the payload'],
      [r`\.[A-Za-z0-9_-]*$`, 'dot, then the signature (empty for `alg: none`)'],
    ],
    caveats: ['This checks shape only. Always verify the signature with a JWT library before trusting the claims.', 'JWE tokens have five segments and will not match.'],
    matches: [
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c',
      'eyJhbGciOiJub25lIn0.eyJzdWIiOiIxIn0.',
      'eyJhIjoxfQ.eyJiIjoyfQ.c2ln',
      'eyJ0eXAiOiJKV1QifQ.e30.abc_-',
    ],
    nonMatches: ['abc.def.ghi', 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0', 'eyJ+/=.x.y', 'eyJ a.b.c'],
  },

  // ---------------------------------------------------------------- dates & times
  {
    name: 'iso-date',
    category: 'dates',
    pattern: r`^\d{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12]\d|3[01])$`,
    flags: '',
    description: 'A calendar date in ISO 8601 `YYYY-MM-DD` form, with month 01 to 12 and day 01 to 31.',
    explanation: [
      [r`^\d{4}`, 'four-digit year'],
      ['-(?:0[1-9]|1[0-2])', 'hyphen and month 01 to 12'],
      [r`-(?:0[1-9]|[12]\d|3[01])$`, 'hyphen and day 01 to 31'],
    ],
    caveats: ['Month lengths are not checked, so `2026-02-31` passes. Parse the date and compare its parts if that matters.'],
    matches: ['2026-10-08', '1999-12-31', '2000-01-01', '2024-02-29'],
    nonMatches: ['2026-13-01', '2026-1-1', '2026/10/08', '2026-10-32', '20261008'],
  },
  {
    name: 'iso-datetime',
    category: 'dates',
    pattern: r`^\d{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12]\d|3[01])T(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z|[+-](?:[01]\d|2[0-3]):?[0-5]\d)?$`,
    flags: '',
    description: 'An ISO 8601 / RFC 3339 date-time: date, `T`, then hours and minutes, with optional seconds, fraction and time-zone offset.',
    explanation: [
      ['YYYY-MM-DD', 'the date part (see iso-date)'],
      ['T', 'the literal date/time separator'],
      [r`(?:[01]\d|2[0-3]):[0-5]\d`, 'hours 00 to 23 and minutes 00 to 59'],
      [r`(?::[0-5]\d(?:\.\d+)?)?`, 'optional seconds with an optional fraction'],
      ['(?:Z|[+-]HH:?MM)?', 'optional `Z` (UTC) or an offset like `+02:00` or `-0500`'],
    ],
    caveats: ['A space instead of `T` is valid in RFC 3339 but rejected here. Allow it with `[T ]`.', 'Leap seconds (`:60`) are rejected.'],
    matches: ['2026-10-08T14:30:00Z', '2026-10-08T14:30', '2026-10-08T14:30:00.123+02:00', '2026-10-08T23:59:59-0500'],
    nonMatches: ['2026-10-08 14:30:00', '2026-10-08T24:00:00Z', '2026-10-08T14:60Z', '2026-10-08', '2026-10-08T14:30:00+2'],
  },
  {
    name: 'time-24h',
    category: 'dates',
    pattern: r`^(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d)?$`,
    flags: '',
    description: 'A 24-hour clock time `HH:MM` with optional `:SS`.',
    explanation: [
      [r`(?:[01]\d|2[0-3])`, 'hours 00 to 23, always two digits'],
      [':[0-5]\\d', 'minutes 00 to 59'],
      [r`(?::[0-5]\d)?`, 'optional seconds 00 to 59'],
    ],
    caveats: ['Single-digit hours (`9:05`) are rejected. Use `(?:[01]?\\d|2[0-3])` to allow them.'],
    matches: ['00:00', '23:59', '09:05:30', '12:00'],
    nonMatches: ['24:00', '9:05', '12:60', '12:00:60', '12-00'],
  },
  {
    name: 'cron-basic',
    category: 'dates',
    pattern: r`^(?:\*|\d+(?:-\d+)?)(?:\/\d+)?(?:,(?:\*|\d+(?:-\d+)?)(?:\/\d+)?)*(?:\s+(?:\*|\d+(?:-\d+)?)(?:\/\d+)?(?:,(?:\*|\d+(?:-\d+)?)(?:\/\d+)?)*){4}$`,
    flags: '',
    description: 'The shape of a classic five-field cron expression (minute, hour, day of month, month, day of week) using `*`, numbers, ranges, steps and lists.',
    explanation: [
      [r`(?:\*|\d+(?:-\d+)?)`, 'one item: `*`, a number, or a range like `1-5`'],
      [r`(?:\/\d+)?`, 'optional step such as `/15`'],
      [r`(?:,item)*`, 'optional comma-separated list of more items'],
      [r`(?:\s+field){4}`, 'four more fields separated by whitespace, five in total'],
    ],
    caveats: [
      'Value ranges are not checked (`99 * * * *` passes).',
      'Names (`MON`, `JAN`), `?`, `L`, `W`, `#`, a seconds field and macros like `@daily` are not supported.',
    ],
    matches: ['* * * * *', '0 9 * * 1-5', '*/15 0-6 1,15 * *', '30 2 1 1,6 0'],
    nonMatches: ['* * * *', '* * * * * *', 'every day', '*/ * * * *', '@daily'],
  },

  // ---------------------------------------------------------------- locale
  {
    name: 'us-zip',
    category: 'locale',
    pattern: r`^\d{5}(?:-\d{4})?$`,
    flags: '',
    description: 'A US ZIP code: five digits, with an optional ZIP+4 extension.',
    explanation: [
      [r`^\d{5}`, 'five digits'],
      [r`(?:-\d{4})?$`, 'optional hyphen and four digits'],
    ],
    caveats: ['This checks format only. Not every five-digit number is an assigned ZIP code.'],
    matches: ['90210', '10001-1234', '00501', '99950'],
    nonMatches: ['1234', '123456', '12345-123', 'ABCDE', '12345 6789'],
  },
  {
    name: 'uk-postcode',
    category: 'locale',
    pattern: r`^[A-Z]{1,2}\d[A-Z\d]? ?\d[A-Z]{2}$`,
    flags: 'i',
    description: 'A UK postcode: outward code (area plus district) and inward code (sector plus unit), with an optional space between.',
    explanation: [
      ['^[A-Z]{1,2}', 'area: one or two letters'],
      [r`\d[A-Z\d]?`, 'district: a digit with an optional letter or digit after it'],
      [' ?', 'optional space'],
      [r`\d[A-Z]{2}$`, 'inward code: a digit and two letters'],
    ],
    caveats: ['A simplified shape. It does not apply the per-position letter rules (for example, Q, V and X never start a postcode), and it does not accept `GIR 0AA`.'],
    matches: ['SW1A 1AA', 'EC1A1BB', 'M1 1AE', 'B33 8TH', 'DN55 1PT'],
    nonMatches: ['12345', 'SW1A-1AA', 'SW1A 1A', 'SWA1 1AA', 'W1A 1AAA'],
  },
  {
    name: 'phone-e164',
    category: 'locale',
    pattern: r`^\+[1-9]\d{1,14}$`,
    flags: '',
    description: 'An international phone number in E.164 format: `+`, a country code that does not start with 0, and at most 15 digits in total.',
    explanation: [
      [r`^\+`, 'a literal plus sign'],
      ['[1-9]', 'country codes never start with 0'],
      [r`\d{1,14}$`, 'the rest of the number, up to 15 digits in total'],
    ],
    caveats: ['No spaces, dashes or parentheses, so normalize the input first.', 'Country-specific lengths are not checked. Use a library such as libphonenumber for real validation.'],
    matches: ['+14155552671', '+442071838750', '+81312345678', '+12'],
    nonMatches: ['14155552671', '+0123456', '+1 415 555 2671', '+1234567890123456', '+'],
  },

  // ---------------------------------------------------------------- numbers & money
  {
    name: 'number-thousands',
    category: 'numbers',
    pattern: r`^-?\d{1,3}(?:,\d{3})*(?:\.\d+)?$`,
    flags: '',
    description: 'A number written with comma thousands separators and an optional decimal part, such as `1,234,567.89`.',
    explanation: [
      ['^-?', 'optional minus sign'],
      [r`\d{1,3}`, 'the first group: 1 to 3 digits'],
      [r`(?:,\d{3})*`, 'any number of comma-plus-three-digit groups'],
      [r`(?:\.\d+)?$`, 'optional decimal fraction'],
    ],
    caveats: ['Numbers with no separators longer than 3 digits (`1234`) are rejected. Allow them with `(?:\\d{1,3}(?:,\\d{3})*|\\d+)`.', 'Many locales swap `,` and `.` or group digits differently. `Intl.NumberFormat` shows the local format.'],
    matches: ['1,000', '1,234,567.89', '999', '-12,345'],
    nonMatches: ['1,00', '1234,567', ',123', '1,234,56', '12,34'],
  },
  {
    name: 'currency',
    category: 'numbers',
    pattern: r`^-?[$€£¥]\s?(?:\d{1,3}(?:,\d{3})+|\d+)(?:\.\d{2})?$`,
    flags: '',
    description: 'A money amount with a leading currency symbol (`$`, `€`, `£`, `¥`), optional thousands separators and an optional two-digit cents part.',
    explanation: [
      ['^-?', 'optional minus sign before the symbol'],
      ['[$€£¥]', 'one currency symbol (inside a character class, `$` is literal)'],
      [r`\s?`, 'optional space'],
      [r`(?:\d{1,3}(?:,\d{3})+|\d+)`, 'either a grouped number like `1,234` or plain digits'],
      [r`(?:\.\d{2})?$`, 'optional cents: exactly two decimals'],
    ],
    caveats: ['Trailing symbols (`12 €`), ISO codes (`USD 5`) and currencies with 0 or 3 decimals are not handled.', 'Do not parse money into floating point. Store integer minor units.'],
    matches: ['$1,234.56', '€99', '£0.99', '$1000', '-$5.00'],
    nonMatches: ['1,234.56', '$1.5', '$1,23', '$', '12$'],
  },
  {
    name: 'credit-card-shape',
    category: 'numbers',
    pattern: r`^(?:\d[ -]?){12,18}\d$`,
    flags: '',
    description: 'A string shaped like a payment card number: 13 to 19 digits, optionally grouped with single spaces or hyphens.',
    explanation: [
      [r`(?:\d[ -]?){12,18}`, '12 to 18 digits, each optionally followed by one space or hyphen'],
      [r`\d$`, 'it must end on a digit, for 13 to 19 digits in total'],
    ],
    caveats: [
      'This checks shape only. Apply the Luhn checksum separately (strip separators, double every second digit from the right, and the sum must be divisible by 10).',
      'Never log or store full card numbers. PCI DSS applies.',
    ],
    matches: ['4111 1111 1111 1111', '4111-1111-1111-1111', '4111111111111111', '378282246310005'],
    nonMatches: ['4111 1111 1111', '4111--1111-1111-1111', 'abcd efgh ijkl mnop', '4111 1111 1111 1111 1111', '4111111111111111 '],
  },
  {
    name: 'lat-long',
    category: 'numbers',
    pattern: r`^[-+]?(?:[1-8]?\d(?:\.\d+)?|90(?:\.0+)?),\s*[-+]?(?:180(?:\.0+)?|(?:1[0-7]\d|[1-9]?\d)(?:\.\d+)?)$`,
    flags: '',
    description: 'A "latitude,longitude" decimal pair, with latitude between -90 and 90 and longitude between -180 and 180.',
    explanation: [
      ['^[-+]?', 'optional sign for the latitude'],
      [r`[1-8]?\d(?:\.\d+)?`, 'latitude 0 to 89.999...'],
      [r`|90(?:\.0+)?`, 'or exactly 90'],
      [r`,\s*`, 'comma with optional spaces'],
      ['[-+]?', 'optional sign for the longitude'],
      [r`180(?:\.0+)?`, 'exactly 180'],
      [r`|(?:1[0-7]\d|[1-9]?\d)(?:\.\d+)?$`, 'or 0 to 179.999...'],
    ],
    caveats: ['Degrees-minutes-seconds notation (`40°42′N`) is not supported.'],
    matches: ['40.7128,-74.0060', '-33.8688, 151.2093', '90,180', '0,0'],
    nonMatches: ['91,0', '45,181', '40.7128', 'abc,def', '45.,10'],
  },

  // ---------------------------------------------------------------- encoding & security
  {
    name: 'hex-color',
    category: 'encoding',
    pattern: r`^#(?:[0-9a-f]{3,4}|[0-9a-f]{6}|[0-9a-f]{8})$`,
    flags: 'i',
    description: 'A CSS hex color in `#rgb`, `#rgba`, `#rrggbb` or `#rrggbbaa` form.',
    explanation: [
      ['^#', 'a leading hash'],
      ['[0-9a-f]{3,4}', 'short form, with or without alpha'],
      ['|[0-9a-f]{6}', 'or the six-digit form'],
      ['|[0-9a-f]{8}', 'or the eight-digit form with alpha'],
      ['$', 'nothing else after it'],
    ],
    caveats: ['Named colors, `rgb()` and `hsl()` are not covered. `CSS.supports("color", value)` checks all of them in a browser.'],
    matches: ['#fff', '#FFFFFF', '#1a2b3c', '#ff000080', '#abcd'],
    nonMatches: ['fff', '#ff', '#12345', '#ggg', '#1234567'],
  },
  {
    name: 'base64',
    category: 'encoding',
    pattern: r`^(?!$)(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$`,
    flags: '',
    description: 'Standard padded Base64 (RFC 4648): complete four-character groups, with optional `=` or `==` padding at the end.',
    explanation: [
      ['^(?!$)', 'lookahead: the string is not empty'],
      ['(?:[A-Za-z0-9+/]{4})*', 'any number of full four-character groups'],
      ['(?:[A-Za-z0-9+/]{2}==', 'a final group of two characters and `==`'],
      ['|[A-Za-z0-9+/]{3}=)?$', 'or three characters and `=`'],
    ],
    caveats: ['Unpadded Base64 and the URL-safe alphabet (`-_`) fail. Use `[A-Za-z0-9_-]` without padding for base64url.', 'Line-wrapped (MIME) Base64 needs the whitespace stripped first.'],
    matches: ['SGVsbG8=', 'SGVsbG8gV29ybGQ=', 'YQ==', 'YWJj'],
    nonMatches: ['', 'SGVsbG8', 'SGVsbG8===', 'SGV sbG8=', 'YQ=a', 'abc$'],
  },
  {
    name: 'strong-password',
    category: 'encoding',
    pattern: r`^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9\s]).{8,}$`,
    flags: '',
    description: 'Checks that a password has at least 8 characters with a lowercase letter, an uppercase letter, a digit and a symbol. Each requirement is a separate lookahead.',
    explanation: [
      ['^(?=.*[a-z])', 'somewhere ahead there is a lowercase letter'],
      ['(?=.*[A-Z])', '...an uppercase letter'],
      [r`(?=.*\d)`, '...a digit'],
      [r`(?=.*[^A-Za-z0-9\s])`, '...a symbol (not a letter, digit or whitespace)'],
      ['.{8,}$', 'and the whole thing is at least 8 characters'],
    ],
    caveats: [
      'NIST SP 800-63B advises against composition rules. Prefer length (12 or more), a check against breached-password lists, and a strength estimator such as zxcvbn.',
      '`.` does not match newlines, which is fine for passwords.',
    ],
    matches: ['Passw0rd!', 'C0mpl3x#Pass', 'aB3$efgh', 'Tr0ub4dor&3'],
    nonMatches: ['password', 'PASSWORD1!', 'Passw0rd', 'Pa0!', 'passw0rd!'],
  },

  // ---------------------------------------------------------------- text
  {
    name: 'trailing-whitespace',
    category: 'text',
    pattern: r`[ \t]+$`,
    flags: 'm',
    description: 'Finds spaces or tabs at the end of any line. Use it with `replace(/[ \\t]+$/gm, "")` to strip them.',
    explanation: [
      [r`[ \t]+`, 'one or more spaces or tabs'],
      ['$', 'end of a line, because of the `m` flag'],
      ['m flag', 'makes `$` match before every `\\n`, not only at the end of the string'],
    ],
    caveats: ['With Windows line endings, `\\r` sits before `\\n` and `$` does not match before it. Use `[ \\t]+(?=\\r?$)` for CRLF files.'],
    matches: ['line ', 'tab\t', 'multi\nline  \nend', '   '],
    nonMatches: ['clean', 'clean\nlines', '', ' leading'],
  },
  {
    name: 'duplicate-words',
    category: 'text',
    pattern: r`\b(\w+)\s+\1\b`,
    flags: 'i',
    description: 'Finds a word repeated twice in a row, such as "the the", including across a line break. A classic proofreading check.',
    explanation: [
      [r`\b(\w+)`, 'group 1: a whole word'],
      [r`\s+`, 'whitespace between them, newlines included'],
      [r`\1\b`, 'the same word again (backreference), ending at a word boundary so "the theory" does not match'],
      ['i flag', 'case-insensitive, so "Hello hello" matches'],
    ],
    caveats: ['Some repeats are correct ("had had", "that that"), so review matches rather than auto-fixing.', '`\\w` is ASCII-only. Use `[\\p{L}\\p{N}_]` with the `u` flag for other scripts.'],
    matches: ['the the', 'This is is a test', 'Paris in the\nthe spring', 'Hello hello'],
    nonMatches: ['the theory', 'no duplicates here', 'the cat the dog', 'a b a'],
  },
  {
    name: 'camelcase-split',
    category: 'text',
    pattern: r`(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])`,
    flags: 'g',
    description: 'Zero-width split points inside camelCase and PascalCase identifiers. `"XMLHttpRequest".split(re)` gives `["XML", "Http", "Request"]`.',
    explanation: [
      ['(?<=[a-z0-9])(?=[A-Z])', 'a position after a lowercase letter or digit and before an uppercase letter (`camel|Case`)'],
      ['|', 'or'],
      ['(?<=[A-Z])(?=[A-Z][a-z])', 'a position inside a run of capitals, just before the last one when a lowercase letter follows (`XML|Http`)'],
      ['g flag', 'needed for `matchAll`. `split` finds every position anyway'],
    ],
    caveats: ['The match is empty (zero-width), so use it with `split`, or with `replace(re, " ")` to add spaces.', 'ASCII letters only.'],
    matches: ['camelCase', 'XMLHttpRequest', 'getHTTPResponse', 'version2Update'],
    nonMatches: ['lowercase', 'UPPERCASE', 'Capitalized', 'snake_case'],
  },
];

/** Look up a pattern entry by name. Returns undefined when not found. */
export function get(name) {
  return patterns.find((p) => p.name === name);
}
