// Regenerates patterns.css, manifest.json and the copy of patterns.js embedded in index.html.
// Run with `npm run build`.
import { readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { names, svg, dataUri, tileSize } from './patterns.js';

const root = fileURLToPath(new URL('.', import.meta.url));

/** Color and opacity baked into the CSS classes (use patterns.js for others). */
export const CSS_DEFAULTS = { color: '#64748b', opacity: 0.35 };

export function renderCss() {
  let css = `/* svg-patterns — generated by build.js, do not edit.
 * Usage: <div class="pattern-dots"></div>
 * Resize with a custom property: style="--pattern-size: 32px" (tile width).
 * Pattern art: CC0 1.0. For other colors use pattern() from patterns.js. */\n`;
  for (const name of names) {
    const { width, height } = tileSize(name);
    const ratio = Math.round((height / width) * 10000) / 10000;
    const h = ratio === 1 ? `var(--pattern-size, ${width}px)` : `calc(var(--pattern-size, ${width}px) * ${ratio})`;
    css += `\n.pattern-${name} {\n  background-image: url("${dataUri(svg(name, CSS_DEFAULTS))}");\n  background-size: var(--pattern-size, ${width}px) ${h};\n}\n`;
  }
  return css;
}

export function renderManifest() {
  const patterns = names.map((name) => {
    const { width, height } = tileSize(name);
    return { name, className: `pattern-${name}`, defaultSize: { width, height } };
  });
  return JSON.stringify({ name: 'svg-patterns', count: patterns.length, cssDefaults: CSS_DEFAULTS, patterns }, null, 2) + '\n';
}

export function renderGalleryScript() {
  const src = readFileSync(join(root, 'patterns.js'), 'utf8')
    .replace(/^export default .*$/m, '')
    .replace(/^export /gm, '');
  return `/* PATTERNS:START */\n${src.trim()}\n/* PATTERNS:END */`;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  writeFileSync(join(root, 'patterns.css'), renderCss());
  writeFileSync(join(root, 'manifest.json'), renderManifest());
  const htmlPath = join(root, 'index.html');
  const html = readFileSync(htmlPath, 'utf8');
  writeFileSync(htmlPath, html.replace(/\/\* PATTERNS:START \*\/[\s\S]*?\/\* PATTERNS:END \*\//, () => renderGalleryScript()));
  console.log(`Built patterns.css with ${names.length} patterns.`);
}
